stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            tree: true
            timestampable: true
            translatable: true
            sluggable: true
            sortable: true