# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - ::Form/fields.html.twig

services:
    twig.extension.date:
        class: Jasny\Twig\DateExtension
        tags:
            - { name: twig.extension }

    twig.extension.pcre:
        class: Jasny\Twig\PcreExtension
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Jasny\Twig\TextExtension
        tags:
           - { name: twig.extension }

    twig.extension.array:
        class: Jasny\Twig\ArrayExtension
        tags:
           - { name: twig.extension }