app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

zimzim_user:
    resource: "@ZIMZIMUserBundle/Resources/config/routing.yml"
    prefix: /

zimzim_tools:
    resource: "@ZIMZIMToolsBundle/Resources/config/routing.yml"
    prefix:   /

zimzim_constructionsite:
    resource: "@ZIMZIMConstructionSiteBundle/Resources/config/routing.yml"
    prefix:   /