security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ ROLE_USER, ROLE_ADMIN ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    google: "/user/login/check-google"
                    facebook: "/user/login/check-facebook"
#                    twitter: "/user/login/check-twitter"
                login_path: /login
                failure_path: /login

                oauth_user_provider:
                    service: zimzim_user_provider
            logout: true
            anonymous: true

        login:
            pattern: ^/login$
            security: false
#            form_login:
#                always_use_default_target_path: true
#                default_target_path: /home/

            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/zimzim/constructionsite/, role : ROLE_ADMIN }
        - { path: ^/zimzim/typeactionitem/, role : ROLE_ADMIN }
        - { path: ^/zimzim/actionitem/, role : ROLE_ADMIN }
