zimzim_constructionsite_constructionsite:
    path:     /
    defaults: { _controller: "AppBundle:AcmeCS:index" }

zimzim_constructionsite_constructionsite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:AcmeCS:show" }

zimzim_constructionsite_constructionsite_new:
    path:     /new
    defaults: { _controller: "AppBundle:AcmeCS:new" }

zimzim_constructionsite_constructionsite_create:
    path:     /create
    defaults: { _controller: "AppBundle:AcmeCS:create" }
    methods:  POST

zimzim_constructionsite_constructionsite_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:AcmeCS:edit" }

zimzim_constructionsite_constructionsite_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:AcmeCS:update" }
    methods:  [POST, PUT]

zimzim_constructionsite_constructionsite_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:AcmeCS:delete" }
    methods:  [POST, DELETE]
